// <auto-generated />
using System;
using GameStoreAPI.Data.Database_Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameStoreAPI.Data.Migrations
{
    [DbContext(typeof(GameStoreDBContext))]
    partial class GameStoreDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GameStoreAPI.Data.Entities.GameProductEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Developer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("GenreID")
                        .HasColumnType("int");

                    b.Property<string>("ImageURL")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MinimumAge")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PlatformID")
                        .HasColumnType("int");

                    b.Property<double>("PriceInEuro")
                        .HasColumnType("float");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("GenreID");

                    b.HasIndex("PlatformID");

                    b.ToTable("GameProducts");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Active = true,
                            Created = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(1987),
                            Description = "The open-world reinvention of the action-adventure Zelda franchise.",
                            Developer = "Nintendo",
                            GenreID = 1,
                            ImageURL = "https://imgur.com/bhfrngj.jpg",
                            MinimumAge = 12,
                            Name = "The Legend of Zelda: Breath of the Wild",
                            PlatformID = 1,
                            PriceInEuro = 59.990000000000002,
                            Publisher = "Nintendo",
                            ReleaseDate = new DateTime(2017, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Stock = 15,
                            Updated = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2030)
                        },
                        new
                        {
                            ID = 2,
                            Active = true,
                            Created = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2039),
                            Description = "The long-awaited next 2D main installment of the legendary Metroid franchise.",
                            Developer = "Mercury Steam, Nintendo EPD",
                            GenreID = 5,
                            ImageURL = "https://imgur.com/pP1Tu0b.jpg",
                            MinimumAge = 12,
                            Name = "Metroid Dread",
                            PlatformID = 2,
                            PriceInEuro = 59.990000000000002,
                            Publisher = "Nintendo",
                            ReleaseDate = new DateTime(2021, 10, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Stock = 15,
                            Updated = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2040)
                        },
                        new
                        {
                            ID = 3,
                            Active = true,
                            Created = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2043),
                            Description = "A brutally difficult action-RPG set in fantasy Feudal Japan.",
                            Developer = "FromSoftware",
                            GenreID = 3,
                            ImageURL = "https://imgur.com/8Eru10D.jpg",
                            MinimumAge = 18,
                            Name = "Sekiro: Shadows Die Twice",
                            PlatformID = 2,
                            PriceInEuro = 59.990000000000002,
                            Publisher = "Activision",
                            ReleaseDate = new DateTime(2019, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Stock = 10,
                            Updated = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2045)
                        },
                        new
                        {
                            ID = 4,
                            Active = true,
                            Created = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2048),
                            Description = "The open-world evolution of the classic action-RPG formula by the developer of Dark Souls.",
                            Developer = "FromSoftware",
                            GenreID = 1,
                            ImageURL = "https://imgur.com/WIdEXTt.jpg",
                            MinimumAge = 16,
                            Name = "Elden Ring",
                            PlatformID = 3,
                            PriceInEuro = 59.990000000000002,
                            Publisher = "Bandai Namco",
                            ReleaseDate = new DateTime(2022, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Stock = 10,
                            Updated = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2049)
                        },
                        new
                        {
                            ID = 5,
                            Active = true,
                            Created = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2052),
                            Description = "The latest installment in Microsoft's scifi shooter franchise.",
                            Developer = "343 Industries",
                            GenreID = 4,
                            ImageURL = "https://imgur.com/tkjN1HC.jpg",
                            MinimumAge = 12,
                            Name = "Halo Infinite",
                            PlatformID = 4,
                            PriceInEuro = 49.979999999999997,
                            Publisher = "Microsoft",
                            ReleaseDate = new DateTime(2022, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Stock = 10,
                            Updated = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2055)
                        },
                        new
                        {
                            ID = 6,
                            Active = true,
                            Created = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2061),
                            Description = "A tough as nails platformer about a girl climbing a mountain.",
                            Developer = "Maddy Makes Games",
                            GenreID = 9,
                            ImageURL = "https://imgur.com/SkvIdhv.jpg",
                            MinimumAge = 7,
                            Name = "Celeste",
                            PlatformID = 1,
                            PriceInEuro = 19.989999999999998,
                            Publisher = "Maddy Makes Games",
                            ReleaseDate = new DateTime(2018, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Stock = 12,
                            Updated = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2062)
                        },
                        new
                        {
                            ID = 7,
                            Active = true,
                            Created = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2065),
                            Description = "The legendary ARPG franchise returns in this open-world installment.",
                            Developer = "Blizzard Entertainment",
                            GenreID = 1,
                            ImageURL = "https://imgur.com/2pfhksO.jpeg",
                            MinimumAge = 18,
                            Name = "Diablo IV",
                            PlatformID = 6,
                            PriceInEuro = 49.990000000000002,
                            Publisher = "Blizzard Entertainment",
                            ReleaseDate = new DateTime(2023, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Stock = 25,
                            Updated = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2067)
                        },
                        new
                        {
                            ID = 8,
                            Active = true,
                            Created = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2073),
                            Description = "Explore the lost ruins of an insectile civilization in this Metroidvania indie masterpiece.",
                            Developer = "Team Cherry",
                            GenreID = 5,
                            ImageURL = "https://imgur.com/ugHdnif.jpeg",
                            MinimumAge = 7,
                            Name = "Hollow Knight",
                            PlatformID = 2,
                            PriceInEuro = 14.99,
                            Publisher = "Team Cherry",
                            ReleaseDate = new DateTime(2017, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Stock = 10,
                            Updated = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2074)
                        },
                        new
                        {
                            ID = 9,
                            Active = true,
                            Created = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2077),
                            Description = "The sequel to Marvel's Spider-Man 2018 PS4 success.",
                            Developer = "Insomniac Games",
                            GenreID = 3,
                            ImageURL = "https://imgur.com/nljVEBu.jpg",
                            MinimumAge = 16,
                            Name = "Spider-Man 2",
                            PlatformID = 3,
                            PriceInEuro = 49.990000000000002,
                            Publisher = "Sony Interactive Entertainment",
                            ReleaseDate = new DateTime(2023, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Stock = 20,
                            Updated = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2078)
                        },
                        new
                        {
                            ID = 10,
                            Active = true,
                            Created = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2083),
                            Description = "A remake of the PS2 classic horror game",
                            Developer = "Bloober Team",
                            GenreID = 6,
                            ImageURL = "https://imgur.com/QwjVC62.jpg",
                            MinimumAge = 18,
                            Name = "Silent Hill 2",
                            PlatformID = 3,
                            PriceInEuro = 69.980000000000004,
                            Publisher = "Sony Interactive Entertainment",
                            ReleaseDate = new DateTime(2024, 10, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Stock = 0,
                            Updated = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2084)
                        },
                        new
                        {
                            ID = 11,
                            Active = true,
                            Created = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2088),
                            Description = "Experience the vastness of the Chernobyl quarantine zone filled with dangerous enemies, lost artifacts and anomalies.",
                            Developer = "GSC Game World",
                            GenreID = 4,
                            ImageURL = "https://imgur.com/GAKQ3Rs.jpg",
                            MinimumAge = 18,
                            Name = "S.T.A.L.K.E.R. 2 - Heart of Chernobyl",
                            PlatformID = 5,
                            PriceInEuro = 69.980000000000004,
                            Publisher = "Microsoft",
                            ReleaseDate = new DateTime(2024, 10, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Stock = 20,
                            Updated = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2089)
                        },
                        new
                        {
                            ID = 12,
                            Active = true,
                            Created = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2092),
                            Description = "Get ready for the next Layton puzzle filled adventure in a steampunk world.",
                            Developer = "Level 5",
                            GenreID = 10,
                            ImageURL = "https://imgur.com/2vt76ij.jpg",
                            MinimumAge = 7,
                            Name = "Professor Layton and the New World of Steam",
                            PlatformID = 1,
                            PriceInEuro = 49.990000000000002,
                            Publisher = "Nintendo",
                            ReleaseDate = new DateTime(2025, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Stock = 0,
                            Updated = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2093)
                        },
                        new
                        {
                            ID = 13,
                            Active = true,
                            Created = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2097),
                            Description = "A wacky and fresh return to 2D platforming Mario action!",
                            Developer = "Level 5",
                            GenreID = 9,
                            ImageURL = "https://imgur.com/jw9ewXs.jpg",
                            MinimumAge = 12,
                            Name = "Super Mario Wonder",
                            PlatformID = 1,
                            PriceInEuro = 48.990000000000002,
                            Publisher = "Nintendo",
                            ReleaseDate = new DateTime(2023, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Stock = 13,
                            Updated = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2098)
                        },
                        new
                        {
                            ID = 14,
                            Active = true,
                            Created = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2101),
                            Description = "Team up with iconic heroes from past Fire Emblem entries in this celebratory entry in the turn-based strategy franchise.",
                            Developer = "Level 5",
                            GenreID = 8,
                            ImageURL = "https://imgur.com/R19vmF9.jpg",
                            MinimumAge = 12,
                            Name = "Fire Emblem: Engage!",
                            PlatformID = 1,
                            PriceInEuro = 49.990000000000002,
                            Publisher = "Nintendo",
                            ReleaseDate = new DateTime(2023, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Stock = 13,
                            Updated = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2102)
                        },
                        new
                        {
                            ID = 15,
                            Active = true,
                            Created = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2106),
                            Description = "Sid Meyer's classic strategy franchise returns in this newest installment.",
                            Developer = "Firaxis Games",
                            GenreID = 8,
                            ImageURL = "https://imgur.com/9lILiqp.png",
                            MinimumAge = 12,
                            Name = "Civilization VI",
                            PlatformID = 6,
                            PriceInEuro = 29.989999999999998,
                            Publisher = "2K",
                            ReleaseDate = new DateTime(2016, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Stock = 12,
                            Updated = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2107)
                        },
                        new
                        {
                            ID = 16,
                            Active = true,
                            Created = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2111),
                            Description = "Assassin's Creed returns to its roots in this historical fiction epic set in Baghdad.",
                            Developer = "Ubisoft Montpellier",
                            GenreID = 2,
                            ImageURL = "https://imgur.com/CQu33Wf.jpg",
                            MinimumAge = 18,
                            Name = "Assassin's Creed: Mirage",
                            PlatformID = 3,
                            PriceInEuro = 49.979999999999997,
                            Publisher = "Ubisoft",
                            ReleaseDate = new DateTime(2024, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Stock = 18,
                            Updated = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2112)
                        },
                        new
                        {
                            ID = 17,
                            Active = true,
                            Created = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2115),
                            Description = "Return to Persia in this new action 2D-platformer in the legendary Ubisoft franchise.",
                            Developer = "Ubisoft Montpellier",
                            GenreID = 5,
                            ImageURL = "https://imgur.com/Yq5btuH.png",
                            MinimumAge = 16,
                            Name = "Prince Of Persia: The Lost Crown",
                            PlatformID = 2,
                            PriceInEuro = 49.979999999999997,
                            Publisher = "Ubisoft",
                            ReleaseDate = new DateTime(2024, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Stock = 20,
                            Updated = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2116)
                        },
                        new
                        {
                            ID = 18,
                            Active = true,
                            Created = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2121),
                            Description = "Race with more than 500 different cars in 20 vibrant environments and try your hand at the new and improved Career mode.",
                            Developer = "Turn 10 Studios",
                            GenreID = 12,
                            ImageURL = "https://imgur.com/NDQnZLg.png",
                            MinimumAge = 12,
                            Name = "Forza Motorsport",
                            PlatformID = 5,
                            PriceInEuro = 74.980000000000004,
                            Publisher = "Microsoft",
                            ReleaseDate = new DateTime(2023, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Stock = 15,
                            Updated = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2122)
                        },
                        new
                        {
                            ID = 19,
                            Active = true,
                            Created = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2126),
                            Description = "Race against new rivals in this back-to-the-roots, stylized entry of Need For Speed.",
                            Developer = "Criterion Software",
                            GenreID = 12,
                            ImageURL = "https://imgur.com/DFOkCoX.jpg",
                            MinimumAge = 12,
                            Name = "Need For Speed: Unbound",
                            PlatformID = 3,
                            PriceInEuro = 29.98,
                            Publisher = "Microsoft",
                            ReleaseDate = new DateTime(2022, 11, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Stock = 10,
                            Updated = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2127)
                        },
                        new
                        {
                            ID = 20,
                            Active = true,
                            Created = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2130),
                            Description = "A brand-new and expanded version of Shin Megami Tensei V. With a new alternate story branch.",
                            Developer = "Atlus",
                            GenreID = 2,
                            ImageURL = "https://imgur.com/JoXhKHF.jpg",
                            MinimumAge = 16,
                            Name = "Shin Megami Tensei V: Vengeance",
                            PlatformID = 1,
                            PriceInEuro = 59.979999999999997,
                            Publisher = "Sega",
                            ReleaseDate = new DateTime(2024, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Stock = 15,
                            Updated = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2131)
                        },
                        new
                        {
                            ID = 21,
                            Active = true,
                            Created = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2134),
                            Description = "Return to the Ancient Greece-inspired world of TitanQuest in this brand-new sequel!",
                            Developer = "Grimlore Games",
                            GenreID = 2,
                            ImageURL = "https://imgur.com/1HjHPRo.jpg",
                            MinimumAge = 12,
                            Name = "Titan Quest II",
                            PlatformID = 6,
                            PriceInEuro = 59.979999999999997,
                            Publisher = "THQ Nordic",
                            ReleaseDate = new DateTime(2024, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Stock = 15,
                            Updated = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2136)
                        },
                        new
                        {
                            ID = 22,
                            Active = true,
                            Created = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2139),
                            Description = "Kratos returns on his Nordic quest in this sequel to the critically acclaimed God of War 2018 reboot.",
                            Developer = "Santa Monica Studios",
                            GenreID = 3,
                            ImageURL = "https://imgur.com/Fmpx5OZ.jpg",
                            MinimumAge = 18,
                            Name = "God of War: Ragnarok",
                            PlatformID = 3,
                            PriceInEuro = 79.980000000000004,
                            Publisher = "Sony Entertainment",
                            ReleaseDate = new DateTime(2024, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Stock = 15,
                            Updated = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2140)
                        },
                        new
                        {
                            ID = 23,
                            Active = true,
                            Created = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2143),
                            Description = "Fight your friends with your favourite Dragon Ball characters in this gorgeous 2D team-based fighter!",
                            Developer = "Arc System Works",
                            GenreID = 11,
                            ImageURL = "https://imgur.com/6ExY4P2.png",
                            MinimumAge = 12,
                            Name = "Dragon Ball: FighterZ",
                            PlatformID = 2,
                            PriceInEuro = 19.98,
                            Publisher = "Bandai Namco Entertainment",
                            ReleaseDate = new DateTime(2024, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Stock = 8,
                            Updated = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2144)
                        },
                        new
                        {
                            ID = 24,
                            Active = true,
                            Created = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2147),
                            Description = "Psychological horror meets southern gothic aesthetics in this full remake of the original game.",
                            Developer = "Pieces Interactive",
                            GenreID = 6,
                            ImageURL = "https://imgur.com/HRONgc9.png",
                            MinimumAge = 18,
                            Name = "Alone In The Dark",
                            PlatformID = 6,
                            PriceInEuro = 59.979999999999997,
                            Publisher = "THQ Nordic",
                            ReleaseDate = new DateTime(2024, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Stock = 8,
                            Updated = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2149)
                        },
                        new
                        {
                            ID = 25,
                            Active = true,
                            Created = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2152),
                            Description = "After 20 years, the non-linear open-world pioneer Outcast franchise returns.",
                            Developer = "Pieces Interactive",
                            GenreID = 1,
                            ImageURL = "https://imgur.com/891a5Kq.jpeg",
                            MinimumAge = 12,
                            Name = "Outcast: A New Beginning",
                            PlatformID = 6,
                            PriceInEuro = 59.979999999999997,
                            Publisher = "THQ Nordic",
                            ReleaseDate = new DateTime(2024, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Stock = 8,
                            Updated = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2153)
                        },
                        new
                        {
                            ID = 26,
                            Active = true,
                            Created = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2156),
                            Description = "High quality Formula 1 racing returns in this yearly installment.",
                            Developer = "CodeMasters",
                            GenreID = 12,
                            ImageURL = "https://imgur.com/WdivjwX.jpg",
                            MinimumAge = 3,
                            Name = "EA Sport: F1 24",
                            PlatformID = 2,
                            PriceInEuro = 79.980000000000004,
                            Publisher = "EA",
                            ReleaseDate = new DateTime(2024, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Stock = 20,
                            Updated = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2158)
                        },
                        new
                        {
                            ID = 27,
                            Active = true,
                            Created = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2161),
                            Description = "Explore farming, mining and even finding love in this farming simulation RPG indie classic!",
                            Developer = "Concerned Ape",
                            GenreID = 7,
                            ImageURL = "https://imgur.com/iVC44nm.png",
                            MinimumAge = 3,
                            Name = "Stardew Valley",
                            PlatformID = 6,
                            PriceInEuro = 14.99,
                            Publisher = "Concerned Ape",
                            ReleaseDate = new DateTime(2016, 2, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Stock = 13,
                            Updated = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2163)
                        },
                        new
                        {
                            ID = 28,
                            Active = true,
                            Created = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2165),
                            Description = "Prepare for a nostalgic throwback to the 90s with this modern, 16-bit JRPG inspired indie RPG.",
                            Developer = "Sabotage Studio",
                            GenreID = 2,
                            ImageURL = "https://imgur.com/zPIM5Ym.jpg",
                            MinimumAge = 7,
                            Name = "Sea Of Stars",
                            PlatformID = 1,
                            PriceInEuro = 39.979999999999997,
                            Publisher = "Sabotage Studio",
                            ReleaseDate = new DateTime(2024, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Stock = 10,
                            Updated = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2167)
                        },
                        new
                        {
                            ID = 29,
                            Active = true,
                            Created = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2170),
                            Description = "Kazuya returns with a vengeance in the new installment of the classic arcade fighter franchise!",
                            Developer = "Bandai Namco Studios",
                            GenreID = 11,
                            ImageURL = "https://imgur.com/BBr6hDH.jpg",
                            MinimumAge = 16,
                            Name = "Tekken 8",
                            PlatformID = 5,
                            PriceInEuro = 74.980000000000004,
                            Publisher = "Bandai Namco Entertainment",
                            ReleaseDate = new DateTime(2024, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Stock = 10,
                            Updated = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2171)
                        },
                        new
                        {
                            ID = 30,
                            Active = true,
                            Created = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2175),
                            Description = "Who is the traitor of the crew? Try and find out in this co-operative multiplayer social game!",
                            Developer = "Inner Sloth",
                            GenreID = 13,
                            ImageURL = "https://imgur.com/JY12lE8.png",
                            MinimumAge = 7,
                            Name = "Among Us",
                            PlatformID = 6,
                            PriceInEuro = 19.98,
                            Publisher = "Inner Sloth",
                            ReleaseDate = new DateTime(2018, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Stock = 10,
                            Updated = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2176)
                        },
                        new
                        {
                            ID = 31,
                            Active = true,
                            Created = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2179),
                            Description = "The Massively Multiplayer Online installment of the Fallout franchise.",
                            Developer = "Bethesda Game Studios",
                            GenreID = 13,
                            ImageURL = "https://imgur.com/JT8biBl.png",
                            MinimumAge = 18,
                            Name = "Fallout 76",
                            PlatformID = 4,
                            PriceInEuro = 12.99,
                            Publisher = "Bethesda",
                            ReleaseDate = new DateTime(2018, 11, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Stock = 12,
                            Updated = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2180)
                        },
                        new
                        {
                            ID = 32,
                            Active = true,
                            Created = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2183),
                            Description = "Collect loot for the Company with your friends and avoid getting fired...if you survive the trip that is.",
                            Developer = "Zeekers",
                            GenreID = 13,
                            ImageURL = "https://imgur.com/uqnSZ39.jpg",
                            MinimumAge = 16,
                            Name = "Lethal Company",
                            PlatformID = 6,
                            PriceInEuro = 9.9900000000000002,
                            Publisher = "Zeekers",
                            ReleaseDate = new DateTime(2018, 11, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Stock = 12,
                            Updated = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2185)
                        });
                });

            modelBuilder.Entity("GameStoreAPI.Data.Entities.GenreEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Created = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2376),
                            Name = "Open-world",
                            Updated = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2380)
                        },
                        new
                        {
                            ID = 2,
                            Created = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2384),
                            Name = "RPG",
                            Updated = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2385)
                        },
                        new
                        {
                            ID = 3,
                            Created = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2387),
                            Name = "Action-Adventure",
                            Updated = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2389)
                        },
                        new
                        {
                            ID = 4,
                            Created = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2391),
                            Name = "First-Person-Shooter",
                            Updated = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2392)
                        },
                        new
                        {
                            ID = 5,
                            Created = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2394),
                            Name = "Metroidvania",
                            Updated = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2395)
                        },
                        new
                        {
                            ID = 6,
                            Created = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2398),
                            Name = "Horror",
                            Updated = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2400)
                        },
                        new
                        {
                            ID = 7,
                            Created = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2402),
                            Name = "Simulation",
                            Updated = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2403)
                        },
                        new
                        {
                            ID = 8,
                            Created = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2405),
                            Name = "Strategy",
                            Updated = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2406)
                        },
                        new
                        {
                            ID = 9,
                            Created = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2408),
                            Name = "Platformer",
                            Updated = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2409)
                        },
                        new
                        {
                            ID = 10,
                            Created = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2412),
                            Name = "Puzzle",
                            Updated = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2414)
                        },
                        new
                        {
                            ID = 11,
                            Created = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2415),
                            Name = "Fighting",
                            Updated = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2417)
                        },
                        new
                        {
                            ID = 12,
                            Created = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2419),
                            Name = "Racing",
                            Updated = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2420)
                        },
                        new
                        {
                            ID = 13,
                            Created = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2422),
                            Name = "Multiplayer",
                            Updated = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2423)
                        });
                });

            modelBuilder.Entity("GameStoreAPI.Data.Entities.OrderEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<string>("GameTitles")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("TotalPriceInEuro")
                        .HasColumnType("float");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Created = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2597),
                            CustomerID = 1,
                            GameTitles = "Elden Ring,GTA6",
                            OrderDate = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2595),
                            TotalPriceInEuro = 150.0,
                            Updated = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2599)
                        },
                        new
                        {
                            ID = 2,
                            Created = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2604),
                            CustomerID = 2,
                            GameTitles = "Super Monkey Ball,Assassin's Creed: Mirage",
                            OrderDate = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2603),
                            TotalPriceInEuro = 80.0,
                            Updated = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2606)
                        },
                        new
                        {
                            ID = 3,
                            Created = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2609),
                            CustomerID = 3,
                            GameTitles = "Final Fantasy VII: Rebirth",
                            OrderDate = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2608),
                            TotalPriceInEuro = 69.989999999999995,
                            Updated = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2610)
                        });
                });

            modelBuilder.Entity("GameStoreAPI.Data.Entities.PlatformEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Platforms");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Created = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2463),
                            Name = "Nintendo Switch",
                            Updated = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2467)
                        },
                        new
                        {
                            ID = 2,
                            Created = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2472),
                            Name = "PlayStation 4",
                            Updated = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2473)
                        },
                        new
                        {
                            ID = 3,
                            Created = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2475),
                            Name = "PlayStation 5",
                            Updated = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2477)
                        },
                        new
                        {
                            ID = 4,
                            Created = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2479),
                            Name = "XBox One",
                            Updated = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2480)
                        },
                        new
                        {
                            ID = 5,
                            Created = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2482),
                            Name = "XBox Series X",
                            Updated = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2484)
                        },
                        new
                        {
                            ID = 6,
                            Created = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2487),
                            Name = "PC",
                            Updated = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2488)
                        });
                });

            modelBuilder.Entity("GameStoreAPI.Data.Entities.ShoppingCartProductEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<int>("GameProductID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("GameProductID");

                    b.HasIndex("UserID");

                    b.ToTable("ShoppingCartProducts");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Amount = 1,
                            Created = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2558),
                            GameProductID = 1,
                            Updated = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2560),
                            UserID = 1
                        },
                        new
                        {
                            ID = 2,
                            Amount = 3,
                            Created = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2566),
                            GameProductID = 1,
                            Updated = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2567),
                            UserID = 2
                        },
                        new
                        {
                            ID = 3,
                            Amount = 1,
                            Created = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2570),
                            GameProductID = 2,
                            Updated = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2571),
                            UserID = 1
                        });
                });

            modelBuilder.Entity("GameStoreAPI.Data.Entities.UserEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Active = true,
                            Created = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2520),
                            Name = "Bart",
                            Updated = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2522)
                        },
                        new
                        {
                            ID = 2,
                            Active = true,
                            Created = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2526),
                            Name = "Illya",
                            Updated = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2527)
                        },
                        new
                        {
                            ID = 3,
                            Active = true,
                            Created = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2529),
                            Name = "Gilles",
                            Updated = new DateTime(2024, 6, 4, 15, 33, 38, 987, DateTimeKind.Local).AddTicks(2531)
                        });
                });

            modelBuilder.Entity("GameStoreAPI.Data.Entities.GameProductEntity", b =>
                {
                    b.HasOne("GameStoreAPI.Data.Entities.GenreEntity", "Genre")
                        .WithMany("GameProducts")
                        .HasForeignKey("GenreID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameStoreAPI.Data.Entities.PlatformEntity", "Platform")
                        .WithMany("GameProducts")
                        .HasForeignKey("PlatformID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Platform");
                });

            modelBuilder.Entity("GameStoreAPI.Data.Entities.ShoppingCartProductEntity", b =>
                {
                    b.HasOne("GameStoreAPI.Data.Entities.GameProductEntity", "GameProduct")
                        .WithMany("ShoppingCartProducts")
                        .HasForeignKey("GameProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameStoreAPI.Data.Entities.UserEntity", "User")
                        .WithMany("ShoppingCartProducts")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameProduct");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GameStoreAPI.Data.Entities.GameProductEntity", b =>
                {
                    b.Navigation("ShoppingCartProducts");
                });

            modelBuilder.Entity("GameStoreAPI.Data.Entities.GenreEntity", b =>
                {
                    b.Navigation("GameProducts");
                });

            modelBuilder.Entity("GameStoreAPI.Data.Entities.PlatformEntity", b =>
                {
                    b.Navigation("GameProducts");
                });

            modelBuilder.Entity("GameStoreAPI.Data.Entities.UserEntity", b =>
                {
                    b.Navigation("ShoppingCartProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
